// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unorsoseyggcunclqgng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVub3Jzb3NleWdnY3VuY2xxZ25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Nzg1NTYsImV4cCI6MjA2MTI1NDU1Nn0.LOzt-ojnDCflFqJs5HLZjEWVAE5BpGdEgDRxhOVsZZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);