// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfkcrrlcwtzhfmokgcip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma2Nycmxjd3R6aGZtb2tnY2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjQ4OTMsImV4cCI6MjA2MTYwMDg5M30.mAsVc45i2H2hzQARwaj1McgnNLlgaHA6MuyQLMkawUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);